#Nhplugin Config
#This plugin was developed by BDX (GitHub: BDXGaming) (Spigot: BDX_)
#This plugin serves as a bridge between the Spigot/Bukkit api and the Nashorn Scripting engine
#This plugin has no intended features other than passing commands and events to the given js file

#The Javascript entrypoint file [DO NOT CHANGE UNLESS USING CUSTOM ENTRY SCRIPT]
fileName: plugins\Nhplugin\main.js

#event handler js file [DO NOT CHANGE UNLESS USING CUSTOM ENTRY SCRIPT]
eventHandlerFileName: eventHandler.js

#Command handler js file [DO NOT CHANGE UNLESS USING CUSTOM ENTRY SCRIPT]
commandHandlerFileName: commandHandler.js

# List of command names that are used by JS, add new names to support command-name tab completion
commandNames:
  - js